app:
  repo: postgres
  rest:
    port: 8080
  grpc:
    port: 44044
db:
  username: postgres
  password: postgres
  port: 5432
  host: localhost
  database: postgres
broker:
  username: dan4a
  password: admin
  port: 5672
  host: localhost